openapi: 3.0.1
info:
  title: Tracker API
  author: Serdiuk Mykyta
  version: '1.0'
servers:
  - url: /api
paths:
  /shipments:
    post:
      parameters:
        - name: quantity
          in: query
          default: 1
          description: Quantity of shipments created
          required: true
          schema:
            type: number
      tags:
        - Shipments
      summary: Add shipments to db using bloom filter
      responses:
        '201':
          description: Success adding shipments with bloom filter
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Shipment'
        '500':
          description: Problem on the server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /shipments/{barcode}: 
    get:
      tags:
        - Shipments
      summary: Check barcode in DB with Bloom Filter
      parameters:
        - name: bacrode
          in: path
          required: true
          description: Barcode for check
          schema:
            type: string
            minLength: 13
            maxLength: 25
      responses:
        '200':
          description: Shipment with barcode found in DB using  bloom filter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shipment'
        '404':
          description: Shipment with barcode not found in DB using bloom filter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Problem on the server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      type: object
      properties:
        message:
          description: Error message
          type: string
    Shipment:
      type: object
      properties:
        barcode:
          description: Shipment Barcode 
          type: string